name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Замените на 'main', если основной бранч так называется.
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Проверить код
        uses: actions/checkout@v2

      - name: Установить JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' 
          
      - name: Собрать проект
        run: mvn clean install  

      - name: Запустить тесты
        run: mvn test  

      - name: Настроить SSH ключ
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H localhost >> ~/.ssh/known_hosts 
  
      - name: Развернуть приложение
        run: |
          ssh -o StrictHostKeyChecking=no klava@localhost 'bash -s' < ./deploy.sh
