name: CI/CD Pipeline

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  
          
      - name: Build project
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H localhost >> ~/.ssh/known_hosts

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no klava@localhost 'bash -s' < ./deploy.sh
