name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Замените на 'main', если основной бранч так называется.
  pull_request:
    branches:
      - master
# джобы (задачи) для выполнения
jobs:
  build-and-test:
    runs-on: ${{ matrix.architecture }} #запуск на разных ОС
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] #разные операционные системы для тестирования
        include:
          - os: ubuntu-latest
            architecture: x64 
          - os: ubuntu-latest
            architecture: arm64
            
    steps:
      - name: Проверить код
        uses: actions/checkout@v3

      - name: Установить JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17' #версия
          distributio: 'adopt' #дистрибутив Java
          architecture: ${{ matrix.architecture }}
          
      - name: Собрать проект
        run: mvn clean install  

      - name: Запустить тесты
        run: mvn test  

      - name: Настроить SSH ключ
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H localhost >> ~/.ssh/known_hosts 
  
      - name: Развернуть приложение
        run: |
          ssh -o StrictHostKeyChecking=no klava@localhost 'bash -s' < ./deploy.sh
