name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Запускаем при пуше в ветку master
  pull_request:
    branches:
      - master  # Запускаем при создании pull request в ветку master

jobs:
  build-and-test:  # Джоб для сборки и тестирования
    runs-on: ubuntu-latest  # Запуск на Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Клонируем репозиторий

      - name: Set up JDK 21
        uses: actions/setup-java@v2  # Устанавливаем JDK 21
        with:
          java-version: '21'  # Версия Java
          distribution: 'temurin'  # Дистрибутив JDK

      - name: Build project
        run: mvn clean install  # Сборка проекта Maven

      - name: Run tests
        run: mvn test  # Запуск тестов Maven

      - name: Check dependencies for vulnerabilities
        run: mvn dependency-check:check  # Проверка на уязвимости зависимостей

      - name: Build Docker image (optional)
        run: docker build -t my-app:${{ github.sha }} .  # Создание Docker-образа
