name: Deploy to Local Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan localhost >> ~/.ssh/known_hosts

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no user@localhost 'bash -s' < ./deploy.sh
