name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Запускаем при пуше в ветку master
  pull_request:
    branches:
      - master  # Запускаем при создании pull request в ветку master

jobs:
  build-and-test:  # Джоб для сборки и тестирования
    runs-on: ${{ matrix.os }}  # Запуск на разных операционных системах, указанных в матрице
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Разные операционные системы для тестирования
        include:
          - os: macos-latest 
            architecture: x64  # Архитектура x64 для macOS
          - os: macos-latest 
            architecture: arm64  # Архитектура arm64 для macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Клонируем репозиторий

      - name: Set up JDK 21
        uses: actions/setup-java@v2  # Устанавливаем JDK 21
        with:
          java-version: '21'  # Версия Java
          distribution: 'temurin'  # Дистрибутив JDK

      - name: Build project
        run: mvn clean install  # Сборка проекта Maven

      - name: Run tests
        run: mvn test  # Запуск тестов Maven

      - name: Check code style
        run: mvn checkstyle:check  # Проверка стиля кода с помощью Checkstyle

      - name: Check dependencies for vulnerabilities
        run: mvn dependency-check:check  # Проверка на уязвимости зависимостей с помощью dependency-check-plugin

      - name: Upload artifact
        uses: actions/upload-artifact@v2  # Загрузка артефактов сборки
        with:
          name: my-artifact  # Имя для артефакта
          path: target/my-artifact.jar  # Путь к артефакту сборки
